export const PRIVATE_NOTIFICATION_CODE = {
  INVITED_TO_HOUSE: 'INVITED_TO_HOUSE',
  INVITED_TO_ROOM: 'INVITED_TO_ROOM',
  REMOVED_FROM_ROOM: 'REMOVED_FROM_ROOM',
  REMOVED_FROM_HOUSE: 'REMOVED_FROM_HOUSE',
  NOTIFY_USER_DEVICE_FALL_DETECTED: 'NOTIFY_USER_DEVICE_FALL_DETECTED',
};
