export const PAGINATION = {
  SMALL: 20,
  MEDIUM: 50,
  LARGE: 100,
  SUPER_LARGE: 500,
};

export const USER_PERMISSIONS = {
  ACCESS: 'ACCESS',
  ASSIGN: 'ASSIGN',
  DELETE: 'DELETE',
  RECEIVE_NOTIFICATION: 'RECEIVE_NOTIFICATION',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  ASSIGN_ROOM_PERMISSION: 'ASSIGN_ROOM_PERMISSION',
};
